name: rt

dependencies:
  - python=3.9
  - pip
  - pip:
    - Django
    - requests
    - beautifulsoup4
    - selenium
    - numpy
    - matplotlib
    - dateparser
    - plotly==5.4.0
    - pandas==1.3.5
    - celery==5.2.3
    - redis==4.1.0
    - gevent==21.12.0
